declare global {
  interface Window {
    Candu: any;
    kapaSettings: any;
    MktoForms2: any;
  }
}

export const LoadCanduScript = (onReady?: () => void) => {
  // SDK already loaded — don't re-inject the script, just run the callback.
  if (window?.Candu?.init) {
    onReady?.();
    return;
  }
  (function (d, params) {
    var script = d.createElement('script');
    script.async = !0;
    script.setAttribute(
      'src',
      'https://cdn.candu.ai/sdk/latest/candu.umd.js?token=' +
        params.clientToken,
    );
    script.onload = function () {
      onReady?.();
    };
    d.head.appendChild(script);
  })(document, {
    clientToken: 'Ef1TIvdnVD',
  });
};

export const LoadKapaScript = () => {
  var script: any = document.createElement('script');
  script.defer = true;
  script.async = true;
  script.src = 'https://widget.kapa.ai/kapa-widget.bundle.js';
  script.setAttribute(
    'data-website-id',
    'ec11e7dc-acad-4227-b339-d0b7d6ed10ef',
  );
  script.setAttribute(
    'data-project-logo',
    'https://rivery.io/wp-content/uploads/2025/05/logo-64.png',
  );
  script.setAttribute('data-project-name', 'Rivery');
  script.setAttribute(
    'data-modal-title',
    'Need assistance with Data Integration?',
  );
  script.setAttribute('data-project-color', '#072B55');
  script.setAttribute('data-button-hide', 'true');
  script.setAttribute('data-user-analytics-fingerprint-enabled', ' true');
  script.setAttribute(
    'data-modal-disclaimer',
    'This AI assistant is powered by kapa.ai (third party tool). Please be aware that any personal or sensitive data you share is at your own risk and subject to the kapa.ai privacy policy. Answers are based on Boomi Data Integration documentation as generated by this AI tool, and use of such answers is at your own discretion.',
  );
  script.setAttribute(
    'data-modal-ask-ai-input-placeholder',
    'Ask me a question about Boomi Data Integration...',
  );
  script.setAttribute(
    'data-uncertain-answer-callout',
    "It looks like I couldn't find a precise answer to your question. For more in-depth help, I recommend reaching out to our support team. Please open a support ticket and one of our experts will get back to you shortly!",
  );
  script.setAttribute('data-user-analytics-fingerprint-enabled', 'true');
  script.setAttribute('data-example-question-button-width', '600px');
  script.setAttribute('data-modal-override-open-id', 'ask-ai-button');
  script.setAttribute('data-answer-cta-button-enabled', 'true');
  script.setAttribute(
    'data-answer-cta-button-link',
    'https://rivery.io/contact-us/',
  );
  script.setAttribute('data-answer-cta-button-text', 'Talk with a Data Expert');
  document.head.appendChild(script);
};
