// Generated by https://quicktype.io

import { ActiveAccountType } from 'containers/AppSettings/AccountTypes';
import { AccountTypes, OID } from '.';
import { TargetTypes } from './rivers.types';

export interface SignupResponse {
  ok: boolean;
  registration: boolean;
  token: string;
  user_email: string;
  user_id: string;
}

export type TokenPayload = {
  refresh_token: string;
  type?: 'refresh_token' | string;
  user_id: OID;
  account_id: OID;
  expiration?: number;
  env_id: string;
  refresh_subscription?: boolean;
};

export enum UserRoles {
  SUPER_ADMIN = 'super_admin',
  ADMIN = 'admin',
  VIEWER = 'viewer',
  DEVELOPER = 'developer',
  DEPLOYMENT_ADMIN = 'deployment_admin',
  MEMBER = 'connection_viewer',
  GLOBAL_OPERATOR = 'global_operator',
}

export enum Plans {
  STARTER = 'Starter',
  PROFESSIONAL = 'Professional',
  ENTERPRISE = 'Enterprise',
  STANDARD = 'standard',
  TRIAL = 'trial',
  BASE_2025 = 'Base',
  PROFESSIONAL_2025 = 'Professional',
  PRO_PLUS_2025 = 'Pro Plus',
  ENTERPRISE_2025 = 'Enterprise',
}
export enum PlansIds {
  STARTER = 'starter',
  STARTER_ANNUAL = 'starter_annual',
  PROFESSIONAL_ANNUAL = 'professional',
  PROFESSIONAL_PAYG = 'professional_payg',
  ENTERPRISE = 'enterprise',
  STANDARD = 'standard',
  TRIAL = 'trial',
  BASE_2025 = 'base_2025',
  PROFESSIONAL_2025 = 'professional_2025',
  PRO_PLUS_2025 = 'pro_plus_2025',
  ENTERPRISE_2025 = 'enterprise_2025',
}

export interface SubscriptionMetadata {
  plan?: PlansIds;
  subscription_start_date: DateType;
  billing_type: string;
  plan_name: Plans;
  subscription_date: string;
  subscription_end_date: string;
  purchased_rpus: number;
  last_modified_date: string;
  account_id?: string;
}

export interface IAccountDetails {
  boomi_account_id?: string;
  account_type: AccountTypes;
  is_active: boolean;
  is_super_admin: boolean;
  is_global_operator: boolean;
  env_id: string;
  owner_email: string;
  activated_at?: number;
  trial_end_date?: number;
  account_name: string;
  max_runs: number;
  role: UserRoles | string;
  disable_targets: boolean;
  scopes: string[];
  main_target: TargetTypes;
  partner: unknown;
  token: string;
  plan?: string;
  days_trial: number;
  registration_date?: number;
  account_settings: AccountSettings;
  subscription_metadata: SubscriptionMetadata;
  show_welcome: boolean;
  is_trial: boolean;
  blocked_by?: string;
  environments_expiration_date: DateType;
}

export interface IUserLogin {
  last_name: string;
  refresh_token: string;
  first_name: string;
  last_login: DateType;
  user_id: OID;
  user_accounts: UserAccount[];
  registration_enabled: boolean;
  login_type: string;
  status_code: number;
  user_email: string;
  is_super_admin: boolean;
  is_super_admin_creator: boolean;
}

export interface DateType {
  $date: number;
}

export interface UserAccount {
  main_target: TargetTypes;
  disable_targets: boolean;
  running_workers: number;
  disabled_environments_at: DateType;
  account_id: string;
  registration_events: number;
  is_active: boolean;
  max_workers: number;
  snowflake_disable_merge_method: boolean;
  environments_enabled: boolean;
  active_account_type: ActiveAccountType;
  environments_enabled_at: DateType;
  env_id: OID;
  _id: OID;
  account_name: string;
  owner_email?: string;
  plan?: string;
  days_trial?: number;
}

export interface AccountSettings {
  max_allowed_environments: number;
  enable_bq_standard_sql: boolean;
  enable_copy_rivers_here: null;
  allow_sub_rivers: boolean;
  enable_kits?: boolean;
  allow_logic_python?: boolean;
  enable_data_quality?: boolean;
  allow_audit_log?: boolean;
  block_custom_schedule?: boolean;
  manage_users_by_sso_only?: boolean;
  enable_oracle_cdc?: boolean;
  allow_boomi_for_sap?: boolean;
  boomi_sso_account?: boolean;
  allow_subscriptions_to_payg?: boolean;
  datasource_types_settings?: any;
  allow_new_environments?: boolean;
  beta_activities?: boolean;
  allow_new_run_river_api?: boolean;
  allow_new_check_run_api?: boolean;
  use_new_river_list?: boolean;
  block_api_access?: boolean;
  max_selected_tables?: number;
  allow_create_new_stt?: boolean;
  allow_AD_users?: boolean;
  allow_recipe?: boolean;
  show_copilot?: boolean;
  enable_activate_river?: boolean;
  allow_usage_notifications?: boolean;
  allow_ai_based_processing?: boolean;
  super_admins_account?: boolean;
  enable_scheduled_retry?: boolean;
  scheduled_retry_max_retries?: number;
  scheduled_retry_delay_minutes?: number;
}

export enum EnvironmentDefault {
  DEFAULT = 'default_env',
}
