import { OID, RiveryDate, RunStatus } from './common.types';
import { InputControl } from './form-controls.types';
import { LabelsSources } from 'modules';

export interface IConnection {
  _id: OID;
  account: OID;
  connection_creation_time: RiveryDate;
  connection_name: string;
  connection_type_id: string;
  connection_type: string;
  connection_update_by: string;
  connection_update_time: RiveryDate;
  cross_id: OID;
  custom_fz?: boolean;
  env_id: OID;
  // icon?: string;
  is_test_connection: boolean;
  is_test_connection_list: boolean;
  last_test_date: RiveryDate;
  size: number;
  updated_by_name: string;
  valid: boolean;
  fz_connection_id?: OID;
  default_bucket?: string;
  fz_target_type_id?: string;
  connection_details?: any[];
}

export interface IDataSourceV1 {
  data_source_type_settings: DatasourceSettings;
  id: string;
  connection_type: string;
  custom_fz?: boolean;
  description: string;
  disable_check_and_save: boolean;
  documentation_url: string;
  labels?: string[];
  icon: string;
  name: string;
  section_id: string[];
  segment: string[];
  status: LabelsSources.ENABLED | LabelsSources.SOON;
  feature_flags: Record<any, any>;
  api_name: string;
}

export interface IDataSource {
  section_datasources: IDataSourceConnection[];
  section_description: string;
  section_name: string;
}

// Generated by https://quicktype.io

export interface IDataSourceConnection {
  data_source_type_settings: DatasourceSettings;
  id: string;
  connection_type: string;
  custom_fz?: boolean;
  description: string;
  disable_check_and_save: boolean;
  doc_url: string;
  allow_high_frequency?: boolean;
  file_types: ConnectionFileTypes;
  force_custom_fz: boolean;
  fz_bucket: null;
  icon: string;
  is_fz_connection: boolean;
  is_test_connection: boolean;
  name: string;
  section_id: string[];
  segment: string[];
  size: number;
  source_doc_url: string;
  status: string;
  ui_rows: InputControl[][] | InputControl[];
  whitelist_ip_msg: string;
  connection_guidance: string;
  defaults: {};
  release_date: number;
}

export interface ConnectionFileTypes {
  bq: string[];
  azure_sql_dwh: string[];
}

export interface DatasourceSettings {
  support_high_frequency: boolean;
  support_custom_table: boolean;
  support_predefined_reports: boolean;
  support_generic_ui: boolean;
  is_new_interface: boolean;
  is_connection_generic_pattern: boolean;
  supported_file_types_per_data_warehouse: any;
  logs_settings: {
    support_logs: boolean;
    logs_start_time: any;
  };
  increment_defaults: any;
  support_sub_rivers: boolean;
}

// Generated by https://quicktype.io

export interface IConnectionType {
  connection_creation_time: RiveryDate;
  is_aws_access_secret_encrypted: boolean;
  deployed_by: OID;
  package_id: OID;
  env_id: OID;
  account_name: string;
  connection_type: string;
  is_fz_connection: boolean;
  connection_update_by: string;
  is_test_connection: boolean;
  custom_fz: boolean;
  connection_desc: string;
  valid: boolean;
  is_password_encrypted: boolean;
  warehouse: string;
  connection_update_time: RiveryDate;
  username: string;
  fz_connection_id: OID;
  aws_access_secret_exists: boolean;
  account: OID;
  password_exists: boolean;
  deployed_at: RiveryDate;
  aws_access_key: string;
  big_modal: boolean;
  last_test_date: RiveryDate;
  region: string;
  connection_name: string;
  connection_type_name: string;
  cross_id: OID;
  deployment_id: OID;
  _id: OID;
  default_bucket: string;
  is_test_connection_list?: boolean;
}

export type TestResponse = {
  request_status: RunStatus;
  results: boolean;
  _id: OID;
};
export type TestResult = {
  order: number;
  test_description: string;
  test_status: RunStatus;
  test_name: string;
  error_msg: string;
  test_result: boolean | string[];
  test_label: string;
};
export type PullTestConnectionResult = {
  run_id: string;
  error_msg: string;
  is_start: boolean;
  request_status: RunStatus;
  results: boolean;
  results_list: TestResult[];
  skip_table_mapping: boolean;
  _id: OID;
};

export interface FileZoneResponse {
  // Code is status_code
  Code: number;
  fz_target_type_id: string;
  targets_list: {
    connection_type: string;
    datasource_type_id: string;
    fz_bucket: string;
    name: string;
    _id: string;
  }[];
}
export interface AWSDetailsResponse {
  // Code is status_code
  stack_url: string;
  stack_account_id: string;
  manual_attached_policy: string;
}
export type FileZoneConnection = {
  connection_name: string;
  connection_type: string;
  is_test_connection: boolean;
  cross_id: OID;
  _id: OID;
};

export interface IConnectionKeyPair {
  connection_type: string;
  account: OID;
  key_name?: string;
  created_at: RiveryDate;
  key_file_name?: string;
  prefix?: string;
  key_pair_id: OID;
  env_id?: OID;
  _id: OID;
  is_key_file?: boolean;
  status?: string;
  connection_username?: string;
  last_modified?: RiveryDate;
  phone_number?: string;
}

// Generated by https://quicktype.io

export interface ISingleKeyPair {
  connection_type: string;
  public_key: string;
  account: OID;
  key_name: string;
  created_at: RiveryDate;
  key_file_name: string;
  prefix: string;
  key_pair_id: OID;
  user_created: OID;
  env_id: OID;
  _id: OID;
  is_key_file: boolean;
}
