// Generated by https://quicktype.io

export interface IEnvironment {
  account: string;
  color: string;
  variables: Record<string, string>;
  environment_name: string;
  updated_at: number;
  is_default: boolean;
  cross_id: string;
  description: string;
  _id: string;
}

export interface IAddEnvironment {
  selectedAccountId: string;
  name: string;
  color: string;
  description: string;
  is_default: boolean;
}

export type EditEnvironment = {
  selectedAccountId: string;
  id: string;
  environment_name?: string;
  color?: string;
  description?: string;
  is_default?: boolean;
};

export interface ID {
  $oid: string;
}
