// Generated by https://quicktype.io

export interface UserRolesResponse {
  status_code: number;
  roles: UserRole[];
  success: boolean;
}

export interface UserRole {
  _id: string;
  name: string;
  description: string;
}
