// Generated by https://quicktype.io

import { OID, RiveryDate } from './common.types';
import { UserRole } from './roles.types';

export interface IUser {
  status: string;
  first_name: string;
  last_name: string;
  registered_by: string;
  invite_time: RiveryDate;
  is_active: boolean;
  update_time: RiveryDate;
  environments: Environments;
  invited_by: string;
  role: string;
  insert_time: RiveryDate;
  invite_status: string;
  invite_sent: boolean;
  _id: OID;
  user_id: string;
  user_name: string;
  user_email: string;
  updated_by: string;
  allow_login_google: boolean;
  allow_login_passowrd: boolean;
  allow_login_sso: boolean;
  super_admin: boolean;
  onboarding: Record<string, Record<string, boolean>>;
  source: string;
  groups: string[];
}

export type Environments = { [key: string]: Environment };
export interface Environment {
  is_default: boolean | null;
  cross_id: OID;
  environment_name: string;
  role: string;
  _id: OID;
}

export interface ITeam {
  _id: string;
  account: string;
  remote_display_name: string;
  display_name: string;
  description: string;
  environments: Record<string, Record<'role', UserRole>>;
  is_all_environment_admin: boolean;
  is_imported: boolean;
  source: 'rivery';

  // This is not an "official" key but we need it for the UI
  is_new: boolean;
}
