import { StatusTypes } from 'api/types';
import {
  ICollectionResponse,
  IDateRange,
  IRiverCreds,
} from './activities.types';

export interface RiverActivitiesRun extends IDateRange, IRiverCreds {
  run_group_id?: string;
  target_name?: string;
  sub_river_id?: string;
}

export interface RiverActivitiesRunResponse
  extends ICollectionResponse<IRiverActivityRun> {
  master_river_id: string;
  next_page: string;
  total_items: number;
  page: number;
  current_page_size: number;
}

export interface IRiverActivityRun {
  run_id: string;
  datasource_id: string;
  error_description: string;
  units: number;
  run_group_id: string;
  status: StatusTypes;
  source_name: string;
  target_name: string;
  start_date_utc: string;
  start_date_in_milliseconds: number;
  end_date_utc: string;
  end_date_in_milliseconds: number;
  sub_river_id: string;
  is_sub_river_run: boolean;
}

// Generated by https://quicktype.io

export interface IRunTasksLog extends ICollectionResponse<IRunTaskParameter> {
  run_id: string;
}

export interface IRunTaskParameter {
  duration: number;
  error_description: string;
  start_date_utc: string;
  start_date_in_milliseconds: number;
  end_date_utc: string;
  end_date_in_milliseconds: number;
  source: string;
  task_id: string;
  task_name: string;
  task_status: string;
  target: string;
  target_table: string;
  input_parameters: InputParameter[];
}

export interface InputParameter {
  name: string;
  value: string;
}

export interface IStepResponse {
  account: string;
  block_type: string;
  code_type: string;
  container: boolean;
  container_type: string;
  end_time: string;
  environment_id: string;
  error_description: string;
  has_log: boolean;
  start_time: string;
  step_index: string;
  step_duration: string;
  step_execution_id: string;
  step_status: string;
  step_id: string;
  loop_iteration_number: number;
}

export interface IRunStepsResponse {
  account_id: string;
  environment_id: string;
  river_cross_id: string;
  run_id: string;
  steps: Record<string, IStepResponse>;
}

export interface ITablesActivityResponse {
  run_group_id: string;
  status: string;
  units: number;
  max_duration_in_milliseconds: number;
  run_date_epoch_milliseconds: number;
  run_date_utc: string;
  run_end_date_epoch_milliseconds: number;
  run_end_date_utc: string;
  running: number;
  canceled: number;
  pending: number;
  failed: number;
  succeeded: number;
  skipped: number;
}
