// Generated by https://quicktype.io

import { OID, RiveryDate, RiveryId } from 'api/types/common.types';

export interface IRiverResponse {
  cross_id: OID;
  river_definitions: RiverDefinitions;
  tasks_definitions: TasksDefinition[];
  _id: OID;
}

export interface RiverDefinitions {
  account: OID;
  group_id: RiveryId;
  updated_by: OID;
  source_type: string;
  updated_by_name: string;
  shared_params: SharedParams;
  river_date_updated: RiveryDate;
  version_id: OID;
  is_locked: boolean;
  river_date_inserted: RiveryDate;
  is_scheduled: boolean;
  river_name: string;
  river_type: string;
  cross_id: OID;
  river_desc: string;
  _id: OID;
  env_id: OID;
  created_by: OID;
}

export interface SharedParams {
  notifications: Notifications;
  fz_connection: FzConnection;
}

export interface FzConnection {}

export interface Notifications {
  on_warning: FzConnection;
  on_failure: FzConnection;
}

export interface TasksDefinition {
  insert_date: RiveryDate;
  version_id: OID;
  env_id: OID;
  update_date: RiveryDate;
  account: OID;
  previous_version: string;
  task_id: OID;
  created_by: OID;
  task_definition: TaskDefinition;
  deployment_id: null;
  _id: OID;
  river_id: OID;
}

export interface TaskDefinition {
  task_label: string;
  related: Related;
  global_keys: GlobalKeys;
  task_type_name: string;
  env_id: OID;
  is_mapping_lock: boolean;
  created_by: OID;
  feeder_module: string;
  task_config: TaskConfig;
  task_type_id: string;
  task_process_module: string;
  is_target_task: boolean;
  river_id: OID;
  ordinal: number;
  datasource_id: string;
  updated_by: OID;
  schedule: Schedule;
  task_method: string;
  pull_translate: PullTranslate;
  connection_id: FzConnection;
  version_id: OID;
  is_synchronized: boolean;
  current_workers_running: number;
  task_date_inserted: RiveryDate;
  account: OID;
  task_date_updated: RiveryDate;
  is_deleted: boolean;
  max_no_of_files: number;
  is_feeder_lock: boolean;
  task_name: string;
  task_display_name: string;
  pull_target: string;
  _id: OID;
  is_worker_lock: boolean;
}

export interface GlobalKeys {
  target_name: string;
}

export interface PullTranslate {
  fields: string;
  datasets: string;
  schemas: string;
  results: string;
  databases: string;
}

export interface Related {
  connections: any[];
  rivers: string[];
}

export interface Schedule {
  endDate_beforeSave: string;
  sched: Sched;
  job_id: string;
  isEnabled: boolean;
  cronExp: string;
  endDate: FzConnection;
  currentTab: string;
}

export interface Sched {
  hour: number;
  min: number;
  year: Year;
  days: Days;
  month: Month;
  hours: Hours;
  showCrontab: boolean;
  minutes: number;
}

export interface Days {
  days: number;
}

export interface Hours {
  hours: number;
  minu: number;
  radioHour: number;
}

export interface Month {
  radioMon: number;
  months: number;
  days: number;
  month: number;
}

export interface Year {
  radioYear: number;
  days: number;
}

export interface TaskConfig {
  logic_steps: LogicStep[];
  condition_name_counter: number;
  step_name_counter: number;
  variables: Variables;
  fz_batched: boolean;
  container_name_counter: number;
  datasource_id: string;
}

export interface LogicStep {
  status: string;
  hash_key_init: string;
  isEnabled: boolean;
  action_results: ActionResult[];
  container_running: string;
  content: Content;
  original_variables: OriginalVariables;
  hideBlock: boolean;
  error_description: string;
  step_name: string;
  step_id: string;
  nodes: any[];
  loadActionRiver: boolean;
}

export interface ActionResult {
  response_details: ResponseDetails;
  name: string;
  results: string;
}

export interface ResponseDetails {
  response_status_code: number;
}

export interface Content {
  execute_sql_command: boolean;
  block_type: string;
  compression: string;
  file_type: string;
  fields: any[];
  fzConnection: FzConnection;
  connection_id: FzConnection;
  drop_after: boolean;
  target_type: string;
  action_vars: ActionVars;
  split_tables: string;
  block_db_type: string;
  output_vars_mapping: OutputVarsMapping;
  split_interval: string;
  type: string;
  block_primary_type: string;
  gConnection: FzConnection;
  use_standard_sql: boolean;
  query_priority: string;
  target_loading: string;
  action_id: string;
  partition_type: string;
  partition_granularity: string;
  is_ordered_merge: boolean;
  order_expression: string;
}

export interface ActionVars {
  action_variables: FzConnection;
  connection_details: FzConnection;
  interval_params: FzConnection;
}

export interface OutputVarsMapping {
  status: string;
}

export interface OriginalVariables {
  output_variables: string[];
  file_type: null;
  action_variables: any[];
  connection: FzConnection;
  connection_details: any[];
  interval_params: any[];
}

export interface Variables {
  oryan_var: OryanVar;
}

export interface OryanVar {
  clear_value_on_start: boolean;
}
