import { IRiverV1 } from 'modules/SourceTarget';
import { ICollectionResponse } from 'store/generic.api.types';

export interface IVersionsResponse extends ICollectionResponse<IRiverVersion> {
  statistics: IVersionStats;
}

export interface IVersionStats {
  bookmarked_versions: number;
  bookmarks_allowed: number;
  total_versions: number;
  snapshot_versions: number;
  versions_allowed: number;
}

// Generated by https://quicktype.io

export interface IRiverVersion {
  account_id: string;
  bookmarked: boolean;
  created_by: string;
  environment_id: string;
  insert_date: string;
  name?: string;
  previous_version: string;
  river_id: string;
  river: RiverVersionDetails;
  user_info: UserInfo;
  version_id: string;
}

// response for single version with river api v1
export interface IRiverVersionData extends Omit<IRiverVersion, 'river'> {
  river: IRiverV1;
}
export interface RiverVersionDetails {
  river_definition: RiverDefinition;
  source_task_config: SourceTaskConfig;
}

export interface RiverDefinition {
  _id: string;
  account: string;
  group_id: GroupID;
  updated_by: string;
  source_type: string;
  shared_params: SharedParams;
  river_date_updated: string;
  is_sub_river: boolean;
  is_master_river: boolean;
  version_id: string;
  is_locked: boolean;
  river_date_inserted: string;
  river_name: string;
  river_type: string;
  cross_id: string;
  river_desc: string;
  env_id: string;
  created_by: string;
  is_scheduled: boolean;
  is_deleted: boolean;
  schedulers: any[];
  is_api_v2: boolean;
  river_status: string;
  deployment_definition: DeploymentDefinition;
}

export interface DeploymentDefinition {}

export interface GroupID {
  _id: string;
}

export interface SharedParams {
  run_timeout: number;
  notifications: Notifications;
  fz_connection: DeploymentDefinition;
}

export interface Notifications {
  on_warning: On;
  on_failure: On;
  on_run_threshold: On;
}

export interface On {
  email: string;
}

export interface SourceTaskConfig {
  _id: string;
  account: string;
  created_by: string;
  env_id: string;
  insert_date: string;
  previous_version: string;
  river_id: string;
  task_definition: TaskDefinition;
  task_id: string;
  update_date: string;
  version_id: string;
}

export interface TaskDefinition {
  _id: string;
  ordinal: number;
  account: string;
  env_id: string;
  river_id: string;
  version_id: string;
  connection_id: DeploymentDefinition;
  feeder_module: string;
  pull_target: string;
  move_as_is: boolean;
  task_process_module: string;
  task_config: TaskConfig;
  task_type_id: string;
  task_type_name: string;
  task_method: string;
  is_deleted: boolean;
  datasource_id: string;
  is_worker_lock: boolean;
  is_feeder_lock: boolean;
  schedule: Schedule;
  deployment_definition: DeploymentDefinition;
}

export interface Schedule {
  endDate: DeploymentDefinition;
  isEnabled: boolean;
  sched: Sched;
  cronExp: string;
}

export interface Sched {
  hour: number;
  min: number;
  showCrontab: boolean;
  days: Days;
  month: Month;
  hours: Hours;
  year: Year;
  minutes: number;
}

export interface Days {
  days: number;
}

export interface Hours {
  hours: number;
  radioHour: number;
}

export interface Month {
  radioMon: number;
  months: number;
  days: number;
  month: number;
}

export interface Year {
  radioYear: number;
  days: number;
}

export interface TaskConfig {
  logic_steps: LogicStep[];
  condition_name_counter: number;
  variables: DeploymentDefinition;
  datasource_id: string;
  fz_batched: boolean;
  container_name_counter: number;
  step_name_counter: number;
}

export interface LogicStep {
  isParallel: boolean;
  isEnabled: boolean;
  container_running: string;
  content: Content;
  step_name: string;
  nodes: any[];
}

export interface Content {
  block_type: string;
  compression: string;
  file_type: string;
  block_primary_type: string;
  target_loading: string;
  connection_id: DeploymentDefinition;
  drop_after: boolean;
  target_type: string;
  block_db_type: string;
  split_interval: string;
  fields: any[];
  split_tables: string;
  sql_query: string;
  target_table: string;
}

export interface UserInfo {
  user_name: string;
  user_email: string;
}
