import { EntityState } from '@reduxjs/toolkit';

export const REDUCER_KEY = '__templateName__';

export interface I__templateNameToPascalCase__State
  extends EntityState<I__templateNameToPascalCase__Entity> {
  selectedId: string;
}

// Generated by https://quicktype.io
export interface I__templateNameToPascalCase__Entity {
  id: string;
}
